pathOUT = output/results
pathParameters = parameters.txt
pathSimulator = output/simulator
pathToSimulatorResultFile = output/simulator/results/results.txt
cuttOfPlanning = 10
typeCuttOfPlanning = INT
