# For all path the folder must be created
pathOUT = ./ResultSim
pathParameters = ./data/simulation/parameters.txt
pathSimulator = ./ResultSim
pathToSimulatorResultFile = ./ResultSim/results.txt
cuttOfPlanning = 10
typeCuttOfPlanning = INT
