# For all path the folder must be created
pathOUT = ./ResultSim
pathParameters = ./data/simulation/parameters.txt
pathSimulator = c:/mySimulator
# the place where the simulator creates automatically results file for a simulation
pathToSimulatorResultFile = c:/mySimulator/results/results.txt
# How many time must the planning run
cuttOfPlanning = 10
# type of cuttOfPlanning : INT, HOURS, MINUTES, DAY, CRITERIA
# INT = iteration or loops
# Criteria = based on the probability. The numbers must be between 1 and 0. ex.:0.5
typeCuttOfPlanning = INT
